### ISSUE TITLE
[REQUEST] Documentation Improvements for MacOS / Playwright

### ISSUE THREAD

**Issue by tbusillo** [Sparticuz/chromium#117]
## What would you like to have implemented?

Note: This is a high-level issue, but I would like to offer to submit a PR generally addressing this issue. First, I wanted to see if a PR on the below would be considered/useful, and if so, what feedback there may be on implementation. 

I would like to see some additions to the existing documentation/examples for setup with ARM-based MacOS systems and Playwright for local development. There is some documentation already included in the existing docs, but the existing example(s) were more Linux oriented and it took digging through a few closed issues/sometimes cryptic errors in order to finally get things running locally. 

A little more specifically, I would like to add some additional details/maybe some troubleshooting steps to [this section of the docs](https://github.com/Sparticuz/chromium#running-locally--headlessheadful-mode). I would also like to include a working example using serverless framework + playwright + ARM-based system in [the examples](https://github.com/Sparticuz/chromium/tree/master/examples). 

## Why would it be useful?

This would be useful to help developers more easily get started with and use the package in a local development environment using a setup that is becoming increasingly common for developers (e.g., M1 + MacOS + Playwright).

**Comment by Sparticuz** [comment]
Sure. I don't have access to an M chip right now, so I won't be much help, hah!

**Comment by tbusillo** [comment]
> Sure. I don't have access to an M chip right now, so I won't be much help, hah!

Cool and totally understand! I will work on a PR and submit hopefully this weekend; feel free to ping me if ever need some user testing on an M1 as well!

**Comment by tbusillo** [comment]
Wanted to provide a quick update and apologies for the delay with this. I just got done with a move and trying to get caught up. Will try to have a PR up for this this weekend!

**Comment by skukan159** [comment]
Has this progressed? I am running into some of the "cyptic" issues and having trouble getting past them.
The current one being:
   should render a page report:
     Error: spawn Unknown system error -8
      at ChildProcess.spawn (node:internal/child_process:413:11)
      at Object.spawn (node:child_process:757:9)
      at new Process (/project/node_modules/.pnpm/@puppeteer+browsers@1.7.0/node_modules/@puppeteer/browsers/lib/cjs/launch.js:113:1)
      at launch (/project/node_modules/.pnpm/@puppeteer+browsers@1.7.0/node_modules/@puppeteer/browsers/lib/cjs/launch.js:66:1)
      at ChromeLauncher.launch (/project/node_modules/.pnpm/puppeteer-core@21.1.0_encoding@0.1.13/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:86:1)
