### ISSUE TITLE
[BUG] Error when extracting binaries

### ISSUE THREAD

**Issue by lucasbesen** [Sparticuz/chromium#123]
## Environment

- `chromium` Version: 112.0.2
- `puppeteer` / `puppeteer-core` Version: 20.4.0
- Node.js Version: 18.x
- Lambda / GCF Runtime: nodejs18.x

## Current Behavior

I'm using `chromium-min` and hosting binaries on S3. The first time I deployed it worked, but it stopped after new deploys. I've tried different binaries, hosts, cleaning `/tmp` directory but nothing worked.

One of my deploys that was cleaning `/tmp` directory worked, but it started failing after a new one.

Any thoughts?

```js
{
    "errorType": "Error",
    "errorMessage": "Unexpected end of data",
    "stack": [
        "Error: Unexpected end of data",
        "    at Extract._final (/var/task/node_modules/tar-stream/extract.js:253:42)",
        "    at callFinal (/var/task/node_modules/readable-stream/lib/_stream_writable.js:590:10)",
        "    at processTicksAndRejections (node:internal/process/task_queues:82:21)"
    ]
}
```

**Comment by lucasbesen** [comment]
For those who have the same issue, make sure your S3 file is public.

**Comment by Baksha2008** [comment]
I use public bucket but got this error. Any solutions?
