### ISSUE TITLE
Chromium executable path not found

### ISSUE THREAD

**Issue by unknown1337** [Sparticuz/chromium#142]
### situation:

1. aws amplify lambda function
2. TS + nextjs module (node)
3. windows
4. package.json: 
```
{
  "name": "CRi............",
  "version": "2.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.js",
  "license": "Apache-2.0",
  "dependencies": {
    "@aws-crypto/sha256-js": "^2.0.1",
    "@aws-sdk/credential-provider-node": "^3.76.0",
    "@aws-sdk/protocol-http": "^3.58.0",
    "@aws-sdk/signature-v4": "^3.58.0",
    "@sparticuz/chromium-min": "116",
    "puppeteer-core": "^21.1.0"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.92"
  },
  "scripts": {
    "build": "tsc -noEmit && esbuild index.ts --main-fields=module,main --bundle --platform=node --external:aws-sdk --external:aws-lambda --external:@aws-sdk/signature-v4-crt --outdir=./"
  }
}
```

### relevant code: 
```
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
   console.log('a')
    console.log(await chromium.executablePath('https://github.com/Sparticuz/chromium/releases/download/v116.0.0/chromium-v116.0.0-pack.tar'))
    const browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath('https://github.com/Sparticuz/chromium/releases/download/v116.0.0/chromium-v116.0.0-pack.tar'), //'C:/Program Files/Google/Chrome/Application/chrome.exe',// see chrome://version/
      headless: chromium.headless,
    });
```

### tried

1. amplify mock function result:
```
extracted
downloaded,, extract to  C:\Users\tim-b\AppData\Local\Temp/chromium-pack
error
AssertionError [ERR_ASSERTION]: protocol mismatch  
    at Object.request4 [as request] (C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:76831:19)
    at Object.get (C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:76836:48)
    at C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:76999:32

    at new Promise (<anonymous>)
    at downloadAndExtract (C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:76993:45)
    at Chromium.executablePath (C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:77191:76)
    at Chromium.executablePath (C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:77191:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async lambdaHandler (C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:93326:17)
    at async runRequest (C:\repos\creativeReportingIterate\amplify\backend\function\puppeteertest2\src\index.js:80485:27) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 'c:',
  expected: 'https:',
  operator: '=='
}
```
2. the folder `C:\Users\tim-b\AppData\Local\Temp/chromium-pack` contains aws.tar.br, chromium.br, switshader.tar.br

 
### main question:
What am I doing wrong? is it correct that the temp chromium pack folder contains .br files in stead of decompressed files?

note, the `extracted
downloaded,, extract to  C:\Users\tim-b\AppData\Local\Temp/chromium-pack` console logs are because i made them in the node packages source code to find the path

**Comment by Sparticuz** [comment]
@unknown1337 This package is for Linux only. It's specifically compiled for serverless environments.
