### ISSUE TITLE
[BUG] Can't get working with deno in AWS Lambda

### ISSUE THREAD

**Issue by 3raser95** [Sparticuz/chromium#172]
## Environment

- `chromium` Version: 117
- `puppeteer` / `puppeteer-core` Version: 21.4.1

## Expected Behavior

The package should be installed and the script ran

## Current Behavior

The AWS Lambda function fails with the following error code
```
Error: The input directory "/_virtual/esm.sh/v133/@sparticuz/chromium@117.0.0/bin" does not exist.
    at Function.executablePath (https://esm.sh/v133/@sparticuz/chromium@117.0.0/denonext/chromium.mjs:18:6013)
    at handler (file:///MY_SCRIPT_FILE)
    at file:///tmp/runtime.js:78:24
    at eventLoopTick (ext:core/01_core.js:165:11)
```

## Steps to Reproduce

```
import puppeteer from "npm:puppeteer-core@21.4.1";
import chromium from "https://esm.sh/@sparticuz/chromium@117.0.0";

chromium.setHeadlessMode = true;
const browser = await puppeteer.launch({
  executablePath: await chromium.executablePath(),
  headless: chromium.headless,
  defaultViewport: chromium.defaultViewport,
  args: chromium.args,
});
```

**Comment by Sparticuz** [comment]
At this point, we're cjs. Looking to change this very soon with the release of node 20 on Lambda.
