### ISSUE TITLE
[BUG]throw an err :Navigating frame was detached in aws lambda

### ISSUE THREAD

**Issue by Forktechai** [Sparticuz/chromium#206]
chromium Version:116
puppeteer / puppeteer-core Version:21.1.0
Node.js Version:16
Lambda / GCF Runtime: public.ecr.aws/lambda/nodejs:16

`page.goto(url, { waitUntil: 'networkidle0' }) ` threw the following exception:

_2023-12-20T01:39:55.514Z	4e30b7ef-9859-4639-a518-b05b3e9cf52f	ERROR	Error: Navigating frame was detached
    at LifecycleWatcher.#onFrameDetached (/var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:47)
    at /var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:1:269
    at Array.map (<anonymous>)
    at Object.emit (/var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:1:252)
    at Frame.emit (/var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:88:22)
    at FrameManager.#removeFramesRecursively (/var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:394:15)
    at /var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:90:46
    at onceHandler (/var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:99:13)
    at /var/task/node_modules/.pnpm/puppeteer-core@21.1.0/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:1:269
    at Array.map (<anonymous>)_

but when i use the base image public.ecr.aws/lambda/nodejs:16.2023.11.10.17   , it works well.

**Comment by Sparticuz** [comment]
You'll need to update to 119.0.2 to get the new libs package.

**Comment by Prinzhorn** [comment]
I'm just in the process of migrating from an ancient chrome-aws-lambda and seeing the same error with `page.goto`. I tried `@sparticuz/chromium@119.0.2` with both `puppeteer-core@21.6.1` and `puppeteer-core@21.5.2`. According to https://pptr.dev/chromium-support one of them should definitely work or no?

**Comment by yoeven** [comment]
I had the same issue and have been on it for the entire day. it seems to be something related with the browser data being created in the `/tmp` directory being shared between lambda function. `await browser.close()` would technically clean up any data without affecting the next run but calling `await browser.close()` stalls sometimes. Here are something I did to fix it:
- Upgrade puppeteer-core to `"puppeteer-core": "^21.10.0"`
- Upgraded @sparticuz/chromium to `"@sparticuz/chromium": "^121.0.0"`
- call `await browser.close()` at the end of the function like this `await Promise.race([browser.close(), browser.close(), browser.close()]);` so that if one call hangs most of the time the others would work to continue the process
- remember to call `await browser.close()` even when your script throws errors for another reason, always close the browser before responding with a status

**Comment by alexander-dermicus** [comment]
Potentially related (with fix): https://github.com/Sparticuz/chromium/issues/229#issuecomment-2084587650
