### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dashcraft** [Sparticuz/chromium#270]
## Environment

- `chromium` Version:     "@sparticuz/chromium": "^119.0.2",
- `puppeteer` / `puppeteer-core` Version: "puppeteer-core": "^21.5.0",
- Node.js Version: nodejs18.17.0
- Lambda / GCF Runtime: nodejs18.x.x

## Expected Behavior
Puppeteer should've launched normally.

## Current Behavior
Recently lambdas on Nodejs18.x.x have started failing to launch the browser process for chromium with the following error:
\"error\":{\"name\":\"TargetCloseError\",\"cause\":{\"name\":\"ProtocolError\"}}

Spartacuz chromium v118.0.0 was previously working fine on lambdas and stopped working.

I attempted to upgrade to run on Spartacuz chromium v123, but it fails to run due to the following error:
Error: spawn ETXTBSY

## Possible Solution
Not sure, there seems to be some child process issues when loading the binary in the latest version which should be fixed.

**Comment by joaodezembro** [comment]
Same problem here. Was also working fine 1 month before

**Comment by acdrDev** [comment]
I had the same problem, apparently there is a new version in the lambda runtime, in this new version are needed the files that are added in version 119.0. 2 of “@sparticuz/chromium”, so if you had a version lower than this and also had to configure the version of the lambda runtime as “Auto” this will take the latest version making you generate an error when launching the browser, can be solved by updating the package “@sparticuz/chromium” to version 119.0.2 or higher (I updated to version 121), or manually adding the ARN of the previous version of the runtime.

**Comment by dashcraft** [comment]
> I had the same problem, apparently there is a new version in the lambda runtime, in this new version are needed the files that are added in version 119.0. 2 of “@sparticuz/chromium”, so if you had a version lower than this and also had to configure the version of the lambda runtime as “Auto” this will take the latest version making you generate an error when launching the browser, can be solved by updating the package “@sparticuz/chromium” to version 119.0.2 or higher (I updated to version 121), or manually adding the ARN of the previous version of the runtime.

I updated to 121 but then i get the error relate to Error: spawn ETXTBSY when trying to load the executable path during browser spawn process.

**Comment by joaodezembro** [comment]
> I had the same problem, apparently there is a new version in the lambda runtime, in this new version are needed the files that are added in version 119.0. 2 of “@sparticuz/chromium”, so if you had a version lower than this and also had to configure the version of the lambda runtime as “Auto” this will take the latest version making you generate an error when launching the browser, can be solved by updating the package “@sparticuz/chromium” to version 119.0.2 or higher (I updated to version 121), or manually adding the ARN of the previous version of the runtime.

For me, it's fixed! Thank you



> > I had the same problem, apparently there is a new version in the lambda runtime, in this new version are needed the files that are added in version 119.0. 2 of “@sparticuz/chromium”, so if you had a version lower than this and also had to configure the version of the lambda runtime as “Auto” this will take the latest version making you generate an error when launching the browser, can be solved by updating the package “@sparticuz/chromium” to version 119.0.2 or higher (I updated to version 121), or manually adding the ARN of the previous version of the runtime.
> 
> I updated to 121 but then i get the error relate to Error: spawn ETXTBSY when trying to load the executable path during browser spawn process.

I'm using the following versions:
- "@sparticuz/chromium": "121.0.0",
- "puppeteer-core": "21.5.2",
- runtime: nodejs18.x
- memorySize: 2048

It's ok now for me

**Comment by acdrDev** [comment]
> > I had the same problem, apparently there is a new version in the lambda runtime, in this new version are needed the files that are added in version 119.0. 2 of “@sparticuz/chromium”, so if you had a version lower than this and also had to configure the version of the lambda runtime as “Auto” this will take the latest version making you generate an error when launching the browser, can be solved by updating the package “@sparticuz/chromium” to version 119.0.2 or higher (I updated to version 121), or manually adding the ARN of the previous version of the runtime.
> 
> I updated to 121 but then i get the error relate to Error: spawn ETXTBSY when trying to load the executable path during browser spawn process.

could you share with me the code with which you are running chromium to try to replicate the error?

**Comment by dashcraft** [comment]
Copying the arn runtime (18.26) worked! runtime (18.28) was definitely causing the issue. For v123, here's a snippet of code that should reproduce the error.

```

import puppeteer from "puppeteer-core";
import chromium from "@sparticuz/chromium";

export async function handle() {
    let path = await chromium.executablePath("https://github.com/Sparticuz/chromium/releases/download/v123.0.1/chromium-v123.0.1-pack.tar")
    let configs = {
        args: chromium.args,    
        defaultViewport: chromium.defaultViewport,
        protocolTimeout: 720_000,
        executablePath: path,
        headless: true
    }

    const browser = await puppeteer.launch(configs);
}

```

This results in an error...:

```
Error Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:421:11)
```

**Comment by acdrDev** [comment]
> Error: spawn ETXTBSY

I was trying in node 18 and 20 but in both cases it worked correctly, to replicate your error I had to lower the memory allocated to 128MB and lower the timeout, maybe this is what was causing the error, could you confirm me if the memory you allocated to the lambda is higher than 512MB.

**Comment by dashcraft** [comment]
I may have some surface area for memory issues, since i'm using sst and not serverless to deploy./
It's got some bloat to it.

![image](https://github.com/Sparticuz/chromium/assets/11915975/f23c7e8f-cfca-447c-8d21-ab317b3f6bbf)

**Comment by BrianBorge** [comment]
We had the same issue happen to us this morning.  We change out our versions of puppeteer-core, @sparticuz/chromium, and runtime to match the versions in the comment here 👉 https://github.com/Sparticuz/chromium/issues/270#issuecomment-2083798654.

This worked for us - thank you @joaodezembro

**Comment by dashcraft** [comment]
@BrianBorge I'll try that out and see if that helps, thanks! I'll report back!

**Comment by AkbarHabeeb** [comment]
@joaodezembro It will be great if you have any suggestions on the compatible versions for the node 16 runtime env?

**Comment by dashcraft** [comment]
@BrianBorge still get the: ETXTBSY error with those settings

**Comment by intxjohann** [comment]
We had the same ProtocolError in lambda
Runtime Version: nodejs:16.v35 failed, nodejs:16.v33 however worked so we changed to this one for now

**Comment by dashcraft** [comment]
The ETXBSY is only when i try to run v119+ and node 18 or node 20. Ideally i'd like to use node 20, but that didn't work when i tried it. I've currently lowered everything to node 18.26 via the runtime management arn technique mentioned and that's unbroken all the scrapers we have running atm.

**Comment by AndreiMotinga** [comment]
this is the error I'm getting

```
Error:  Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:762:9)
    at new Process (/Users/andrei.motinga/dev/backend/pdf-generator/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:103:56)
    at launch (/Users/andrei.motinga/dev/backend/pdf-generator/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:50:12)
    at ChromeLauncher.launch (/Users/andrei.motinga/dev/backend/pdf-generator/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:77:54)
    at async getBrowser (webpack-internal:///./src/helpers/getBrowser.ts:11:21)
    at async buildFromHtml (webpack-internal:///./src/buildFromHtml.ts:10:19)
    at async generatePdfFromHtml (webpack-internal:///./src/pdfFromHtmlGenerator.ts:38:21)
    at async handler (webpack-internal:///./handler.ts:19:20)
    at async MessagePort.<anonymous> (file:///Users/andrei.motinga/dev/backend/pdf-generator/app/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}
```

I have this file

```
import { type Browser, launch } from 'puppeteer-core';

import chromium from '@sparticuz/chromium';

const getBrowser = async (): Promise<Browser> => {
  const browser = await launch({
    args: chromium.args,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });

  return browser;
};

export default getBrowser;
```

I was thinking it's an intel vs silicon issue.  if I replace `await chromium.executablePath()` with output of my `which chromium` , as in 

```
import { type Browser, launch } from 'puppeteer-core';

import chromium from '@sparticuz/chromium';

const getBrowser = async (): Promise<Browser> => {
  const browser = await launch({
    args: chromium.args,
    executablePath: '/opt/homebrew/bin/chromium',
    headless: chromium.headless,
  });

  return browser;
};

export default getBrowser;
```
this is new project to me, I'm not sure how to debug this.

what would be an appropriate way to fix this?

**Comment by Sparticuz** [comment]
This package only works on x86 at the moment.

**Comment by AndreiMotinga** [comment]
yeah, sorry, just sorted that. I noticed there is note on [readme](https://github.com/Sparticuz/chromium?tab=readme-ov-file#running-locally--headlessheadful-mode). following that approach for now
