### ISSUE TITLE
[BUG] Cannot extract .tar from S3 endpoint + chromium.executablePath after esbuild

### ISSUE THREAD

**Issue by naemtl** [Sparticuz/chromium#324]
## Environment

- `chromium` Version: "@sparticuz/chromium-min": "^131.0.1"
- `puppeteer` / `puppeteer-core` Version: "puppeteer-core": "^23.10.4"
- Node.js Version: 22.x
- Lambda / GCF Runtime: nodejs22x

## Expected Behavior

Being able to use Puppeteer with Chromium over Lambda. `chromium.executablePath` should read .tar from public S3 successfully.

## Current Behavior

Here's my error from Lambda execution log and log output: 

```
{
  "errorType": "Error",
  "errorMessage": "Unexpected end of data",
  "trace": [
    "Error: Unexpected end of data",
    "    at Extract._final (/var/task/dist/index.cjs:18558:36)",
    "    at WritableState.updateNonPrimary (/var/task/dist/index.cjs:17267:18)",
    "    at WritableState.update (/var/task/dist/index.cjs:17259:76)",
    "    at WritableState.updateWriteNT (/var/task/dist/index.cjs:17554:14)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)"
  ]
}
```

```
START RequestId: 49269209-a644-48ce-9a63-f4af6a8d99d0 Version: $LATEST
2024-12-14T23:22:12.801Z	49269209-a644-48ce-9a63-f4af6a8d99d0	INFO	Connected successfully to MongoDB
2024-12-14T23:22:12.820Z	49269209-a644-48ce-9a63-f4af6a8d99d0	INFO	Connected successfully to MongoDB
2024-12-14T23:22:13.099Z	49269209-a644-48ce-9a63-f4af6a8d99d0	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Unexpected end of data","stack":["Error: Unexpected end of data","    at Extract._final (/var/task/dist/index.cjs:18558:36)","    at WritableState.updateNonPrimary (/var/task/dist/index.cjs:17267:18)","    at WritableState.update (/var/task/dist/index.cjs:17259:76)","    at WritableState.updateWriteNT (/var/task/dist/index.cjs:17554:14)","    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)"]}
END RequestId: 49269209-a644-48ce-9a63-f4af6a8d99d0
REPORT RequestId: 49269209-a644-48ce-9a63-f4af6a8d99d0	Duration: 781.04 ms	Billed Duration: 782 ms	Memory Size: 512 MB	Max Memory Used: 128 MB	Init Duration: 679.73 ms	Status: error	Error Type: Runtime.ExitError
```

## Steps to Reproduce

Here's the `puppeteer.launch` setup I'm using now: 

```
const chromiumS3Url: string = "https://mybucketname.myregion.amazonaws.com/chromium.tar";
const browser: Browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(chromiumS3Url),
      headless: chromium.headless,
    })
```
Using this results in the error above. 

I've written my function in TS, and I'm building/compiling into JS using this command via `esbuild`, then zip my dist/ folder along with my node_modules, and then upload to my Lambda. Perhaps the build process is the issue?

```
npx esbuild index.ts --bundle --platform=node --target=node22 --outfile=dist/index.cjs --format=cjs --external:MongoDB
zip -r function.zip dist/ node_modules/
```

Here's what puppeteer.launch looks like after `esbuild` compiles it:

```
var import_chromium_min2 = __toESM(require_build(), 1);
...
    const browser = await puppeteer_core_default.launch({
      args: import_chromium_min2.default.args,
      defaultViewport: import_chromium_min2.default.defaultViewport,
      executablePath: await import_chromium_min2.default.executablePath(chromiumS3Url),
      headless: import_chromium_min2.default.headless
    });
...
```
Is this the issue?

**Comment by naemtl** [comment]
@Sparticuz appreciate your work, please let me know if you have a suggestion
