### ISSUE TITLE
[BUG] The input directory "/var/bin" does not exist

### ISSUE THREAD

**Issue by rajkrajpj** [Sparticuz/chromium#41]
## Environment
* `chromium` Version: 109.0.1
* `puppeteer` / `puppeteer-core` Version: 19.4.0
* Node.js Version:  v18.12.0
* Lambda / GCF Runtime:  nodejs18.x

## Expected Behavior
https://github.com/Sparticuz/chromium/issues/24#issuecomment-1366863330

## Current Behavior

```
The input directory \"/var/bin\" does not exist.
```

## Steps to Reproduce

```
const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath("/var/bin"),
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
```

**Comment by Sparticuz** [comment]
Does `/var/bin` exist in the function's container? I'll need way more context in order to help

**Comment by rajkrajpj** [comment]
Thanks for the response I appreciate the help @Sparticuz .

I've created the `/var/bin` directory with the `chromium.br` file inside in both the root and relative directory of the lambda function.
![Screen Shot 2023-01-19 at 4 14 10 AM](https://user-images.githubusercontent.com/89990133/213261516-6ee1bb1a-6dbd-4f9d-8266-b0569ba1b980.png)

I've copied the same `chromium.br` file from the node_modules.

![Screen Shot 2023-01-19 at 4 14 43 AM](https://user-images.githubusercontent.com/89990133/213261625-17115d5a-ed7a-4e8b-8310-83a705be3b88.png)

Please let me know if my understanding to your reply is correct 🙏

**Comment by Sparticuz** [comment]
adding it to var/bin inside the function will add it to the functions working directory, not to /var/bin. If you open terminal and go to that folder, you can type `pwd` and it will give you the path you are looking for. Though, if you are uploading the br files in the function, I'm not sure what the benefit is over just using the default.

**Comment by rajkrajpj** [comment]
Thanks for clarifying and for the suggestion @Sparticuz .

I've followed your advise changing it to:
```
executablePath: await chromium.executablePath('var/bin')
```
Alongside other different input attempts, it did not work.

I suspected that the chromium binary file (chromium.br?), is not being copied into the source code upon serverless deployment.

I've validated my assumptions by:
1. copying the `chromium.br` file to the same directory where my lambda handler is
2. logging all relative files to check if its there - **its not there**

Would you know what I need to do to make the `chromium.br` file (and other binary files needed) be copied when I deploy?

I appreciate your help thank you so much 🙏

**Comment by rajkrajpj** [comment]
Following above's comment - 

I verified that the `/bin` directory was not existing in the presence of the lambda environment.
It is existing in my local node_modules though

**Comment by gbanis** [comment]
> I've been able to solve the issue by including the locally installed dependency in the serverless deployment.
> 
> ```
> include:
>     - node_modules/@sparticuz
> ```

Where do you add this? I'm using AWS SAM and I can't figure if/where it would go in `template.yaml`?

**Comment by gbanis** [comment]
Not sure if this is a hack or what but here's how I made it work with AWS SAM:

- Followed the instructions under `AWS Lambda Layer` from [here](https://www.npmjs.com/package/@sparticuz/chromium).
- Added a layer in my function's template pointing to the layer just created in previous step
- Added `"puppeteer-core": "^19.6.0"` and `"@sparticuz/chromium": "^110.0.0"` as dev dependencies
- Pointed the executable path to here `executablePath: await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin')`

Hope this helps the next noob like myself trying to make this work.

**Comment by Sparticuz** [comment]
Interesting, you shouldn't have needed to do that. You are specifically pointing to the layer location.

**Comment by 5neaX** [comment]
@rajkrajpj  , @Sparticuz or anyone else. I have been stuck on trying to run my webscraper on AWS for 2 weeks now trying everything. Ive tried all chrome-aws-lambda, sparticuz aws lambda etc and  got to this after reading through the internet. Now this is my setup

after typing 'npm ls' you can see these are my dependencies 

C:\Users\glenn
├── @sparticuz/chromium@109.0.1
└── puppeteer-core@19.4.1

 Im using Node.js Version: v18.12.0

Lambda / GCF Runtime: nodejs18.x

Memory
2048MB
Ephemeral storage
2048MB

my index.js file is as bellow which runs a function called scraper in scrape.js

`const scraper  = require('./scrape.js');

exports.handler = async (event) => {
    const data = await scraper();
    return {
        statusCode: 200,
        body: JSON.stringify(data),
    };
};
`
I zipped these (package.json, package-lock, node_modules, index.js , scrape.js) and uploaded to s3 and used the s3 url to add the code to the lambda function. 

In the scraping code before the bowser launched i have a console.log so i know everything works up until there. However the error occurs straight after and it doesnt seem like the browser is launching when i hit test. I get this error 

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/57161419/215697889-ae90fb7e-cdd0-49f6-90a2-cc9eea6438db.png">


and this is what ive used to open the browser 


` await (async () => {
       const browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath("/var/task/node_modules/@sparticuz/chromium/bin"),
        headless: chromium.headless,
        ignoreHTTPSErrors: true,
       }).catch((error) => {console.log(error);
      });`

please note in the executable path ive tried leaving is empty (), writing var/bin, and what is in there currently  is what I saw according your last post here. Im not quite sure what to put here and how to find out how, and if this fixes the problem

Could you or anyone please explain what the solution is and how I can finally overcome this in a simple way possible considering im  average at coding? Do i need to copy and paste chromium.br somewhere else ??

will buy you a case of beers if you can solve this XD



thanks

Glenn,

glennmathewthorn@gmail.com

**Comment by 5neaX** [comment]
> I've been able to solve the issue by including the locally installed dependency in the serverless deployment.
> 
> ```
> include:
>     - node_modules/@sparticuz
> ```

Hey, im a little confused about this step specifically as it appears to be what i need to do to solve the problem? how to I include the locally instaled dependency in the serverless deployment ?

**Comment by JobaDiniz** [comment]
> * Pointed the executable path to here `executablePath: await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin')`

I faced the same error: `The input directory \"/var/bin\" does not exist.`.

@gbanis I'm another noob myself, and you saved my day. However, I do know **why** this is the case. Maybe it should be documented in the Readme.

But I wonder how people deal with layers in SAM. I had to manually create the bucket, and then manually download the artifact from the [release](https://github.com/Sparticuz/chromium/releases/tag/v110.0.0), and then manually run the command
```
bucketName="chromiumUploadBucket" && \
aws s3 cp chromium-v110.0.0-layer.zip "s3://${bucketName}/chromiumLayers/chromium-v110.0.0-layer.zip" && \
aws lambda publish-layer-version --layer-name chromium --description "Chromium v110.0.0" --content "S3Bucket=${bucketName},S3Key=chromiumLayers/chromium-v110.0.0-layer.zip" --compatible-runtimes nodejs --compatible-architectures x86_64
```

I still didn't figure it out how make that part of SAM or automatic.

**Comment by buithaibinh** [comment]
I encountered a similar issue, and the solution was to exclude '@sparticuz/chromium' from the bundled lambda. Here's a code snippet using CDK:

```typescript
bundling: {
  externalModules: ['aws-sdk', '@sparticuz/chromium'] // Add any external modules here
},
```

**Comment by ktwbc** [comment]
> Not sure if this is a hack or what but here's how I made it work with AWS SAM:
> 
> * Followed the instructions under `AWS Lambda Layer` from [here](https://www.npmjs.com/package/@sparticuz/chromium).
> * Added a layer in my function's template pointing to the layer just created in previous step
> * Added `"puppeteer-core": "^19.6.0"` and `"@sparticuz/chromium": "^110.0.0"` as dev dependencies
> * Pointed the executable path to here `executablePath: await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin')`
> 
> Hope this helps the next noob like myself trying to make this work.

I was getting Error: The input directory "/var/task/src/bin" does not exist. at Function.executablePath with an empty await chromium.executablePath() when deployed on a node18 lambda using the lambda layer method and 
"@sparticuz/chromium": "^113.0.1",
 "puppeteer-core": "20.5.0",

chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin') fixes it, not sure why it was unable to find the path alone, it was resolving as undefined

**Comment by nicolavs** [comment]
> Not sure if this is a hack or what but here's how I made it work with AWS SAM:
> 
> Followed the instructions under AWS Lambda Layer from [here](https://www.npmjs.com/package/@sparticuz/chromium).
> Added a layer in my function's template pointing to the layer just created in previous step
> Added "puppeteer-core": "^19.6.0" and "@sparticuz/chromium": "^110.0.0" as dev dependencies
> Pointed the executable path to here executablePath: await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin')
> Hope this helps the next noob like myself trying to make this work.


i'm following this 
with this setup 

"@sparticuz/chromium": "123.0.1",
"puppeteer-core": "22.12.1",
 Node.js Version: v18.12.0

Lambda Runtime: nodejs18.x

Memory
2048MB
Ephemeral storage
2048MB


I'm not getting Error: The input directory "/var/task/src/bin" 
but the task timeout after 30s, usually only takes 2s

**Comment by RRACI-Blerand** [comment]
> Does `/var/bin` exist in the function's container? I'll need way more context in order to help

Hello @Sparticuz please help me with this error :
chromium error { e: error: the input directory "/var/task/node_modules/@sparticuz/chromium/bin" does not exist.

This is happening when my function is uploaded in lambda , I am using Nodejs serverless configuration.

It has been a week that i try to fix it but no luck.

Best regards.

**Comment by Sparticuz** [comment]
> > Does `/var/bin` exist in the function's container? I'll need way more context in order to help
> 
> Hello @Sparticuz please help me with this error :
> chromium error { e: error: the input directory "/var/task/node_modules/@sparticuz/chromium/bin" does not exist.
> 
> This is happening when my function is uploaded in lambda , I am using Nodejs serverless configuration.
> 
> It has been a week that i try to fix it but no luck.
> 
> Best regards.
> 

Make sure you either have this package as a dependency or you have it as a layer

**Comment by RRACI-Blerand** [comment]
> /var/task/node_modules/@sparticuz/chromium/bin

Actually when i downloaded the function from lambda as zip i noticed the bin folder was missing from you library (/node_modules/@sparticuz/chromium/bin) => bin folder missing i have no clue how that happened since locally it is there .
My guess is that when i am deploying to lamda something is happening there ?!

**Comment by Sparticuz** [comment]
@RRACI-Blerand You should be able to just deploy the zip itself as a layer. If you are using a bundler you'll need to include it in the bundle somehow. Each bundler is different

**Comment by RRACI-Blerand** [comment]
> @RRACI-Blerand You should be able to just deploy the zip itself as a layer. If you are using a bundler you'll need to include it in the bundle somehow. Each bundler is different

I tried to modify the zip but when i try to compress it again it is exceeding 50Mb limit, maybe i am not compressing it right ?

**Comment by RRACI-Blerand** [comment]
> @RRACI-Blerand You should be able to just deploy the zip itself as a layer. If you are using a bundler you'll need to include it in the bundle somehow. Each bundler is different

Hi there @Sparticuz  i managed to upload the function into s3 bucket then from there upload as zip into my lambda function and there is nothing missing from the libraries now, however i have an error now would you be so kind to assist me please.

ERROR	Error: Error: Navigating frame was detached
    at #onFrameDetached (/var/task/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:103:47)
    at /var/task/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (/var/task/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
    at CdpFrame.emit (/var/task/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
    at #removeFramesRecursively (/var/task/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:450:15)
    at #onClientDisconnect (/var/task/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:94:42)

**Comment by kieronjmckenna** [comment]
Can confirm that [#41 (comment)](https://github.com/Sparticuz/chromium/issues/41#issuecomment-1407545726) did the trick for me as well.

Randomly starting getting this error after a deploy, but specifying the chromium path fixed it

**Comment by bryankocol** [comment]
The easiest solution for me was to use a pre-built Lambda Layer, a list which can be found [here](https://github.com/shelfio/chrome-aws-lambda-layer).  Once added, there is no need to change the executablePath in your code. You can include @sparticuz/chromium as a dependency, but exclude it from the sam build. Example yml:

`ExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Layers:
        - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:50
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        External:
          - "@sparticuz/chromium"`
