### ISSUE TITLE
[BUG] Error running Serverless Framework example (Cannot find module 'extract-zip')

### ISSUE THREAD

**Issue by kepello** [Sparticuz/chromium#60]
## Environment
* `chromium` Version: 110
* `puppeteer` / `puppeteer-core` Version: 19.6.0
* Node.js Version:  16.19.0
* Lambda / GCF Runtime:  nodejs18.x

## Expected Behavior
Sample should run as described.

## Current Behavior
AWS Lambda reports the following error:

Response
```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'extract-zip'\nRequire stack:\n- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js\n- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js\n- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js\n- /var/task/index.js\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'extract-zip'",
    "Require stack:",
    "- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js",
    "- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js",
    "- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js",
    "- /var/task/index.js",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
    "    at async start (file:///var/runtime/index.mjs:1200:23)",
    "    at async file:///var/runtime/index.mjs:1206:1"
  ]
}
```

## Steps to Reproduce

1. Create new folder, add package.json, index.js and serverless.xml from sample found here:  https://github.com/Sparticuz/chromium/tree/master/examples/serverless-with-lambda-layer
2. download ZIP file from releases
3. modify serverless.yml to point to downloaded chromium ZIP file from releases 
      ```
      layers:
        chromiumtest:
          package:
            artifact: ../chromium/chromium-v110.0.1-layer.zip
      ```
4. Run sls deploy
5. From AWS Run test lambda.  Note error.

**Comment by kepello** [comment]
Please ignore this.  I didn't realize that I was working inside a directory that was a couple of levels down in a workspace.  Because of this NPM wasn't placing all the node_modules locally, they were hoisted.  SLS didn't therefore deploy them.

My bad!  My apologies!
