### ISSUE TITLE
[BUG] executablePath error using node18.x on AWS Lambda

### ISSUE THREAD

**Issue by ShlomoVinny** [Sparticuz/chromium#88]
## Environment

* Versions: 
* "@sparticuz/chromium": "^107.0.0"
*  "puppeteer-core": "^19.6.0",
*  "puppeteer-extra": "^3.3.4",
* "puppeteer-extra-plugin-stealth": "^2.11.1",
* Node.js Version: 18.x
* Lambda / GCF Runtime: AWS Lambda node18.x

## Expected Behavior

The script should have launched a headless browser, do some stuff and then timeout on navigation since im only testing to see that chromium launches properly rather than the script running without errors.

<center>**@Sparticuz/chromium works PERFECTLY FINE with node16.x on AWS Lambda!**</center>

All I did was change the runtime from node16.x to node18.x, and it broke.

## Current Behavior

I get this error:
```
2023-04-20T20:53:50.103+03:00	2023-04-20T17:53:50.102Z [34m8[0m [32minfo[39m: App started[31m[0m[31m[0m
2023-04-20T20:53:50.109+03:00	2023-04-20T17:53:50.109Z [34m8[0m [32minfo[39m: Launch headless browser[31m[0m[31m[0m
2023-04-20T20:53:50.110+03:00	2023-04-20T17:53:50.110Z	f1d8d4f0-cc13-44b5-92d0-8fcaf00215f6	INFO	Headless: true
2023-04-20T20:53:53.210+03:00	2023-04-20T17:53:53.210Z	f1d8d4f0-cc13-44b5-92d0-8fcaf00215f6	INFO	
2023-04-20T20:53:53.212+03:00	2023-04-20T17:53:53.212Z	f1d8d4f0-cc13-44b5-92d0-8fcaf00215f6	ERROR	Error: Failed to launch the browser process!
                             	/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
                             	
                             	
                             	TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
                             	
                             	    at onClose (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:300:20)
                             	    at Interface.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:288:24)
                             	    at Interface.emit (node:events:525:35)
                             	    at Interface.close (node:internal/readline/interface:533:10)
                             	    at Socket.onend (node:internal/readline/interface:259:10)
                             	    at Socket.emit (node:events:525:35)
                             	    at endReadableNT (node:internal/streams/readable:1359:12)
                             	    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-04-20T20:53:53.228+03:00	2023-04-20T17:53:53.228Z	f1d8d4f0-cc13-44b5-92d0-8fcaf00215f6	DEBUG	error while getting callsite source context: ENOENT: no such file or directory, open '/opt/nodejs/node_modules/puppeteer-core/src/node/BrowserRunner.ts'
2023-04-20T20:53:53.228+03:00	2023-04-20T17:53:53.228Z	f1d8d4f0-cc13-44b5-92d0-8fcaf00215f6	DEBUG	error while getting callsite source context: ENOENT: no such file or directory, open '/opt/nodejs/node_modules/puppeteer-core/src/node/BrowserRunner.ts'
```

## Steps to Reproduce

Assuming I packaged the layer correctly, (and I did since it does work with node16.x).
Create a new Lambda function using the new node18.x runtime.
Upload the package that includes @Sparticuz/chromium in it to a new layer.
Add the layer to the new Lambda function and launch a headless chromium instance like you normally would.

### Personal note:

I dont know if this is a problem with @Sparticuz/chromium or not, but I would rather start here, since the error does point to chromium missing, or some binaries within it are missing, I dont know.

**Comment by Sparticuz** [comment]
Looks like it's not extracting the aws pack of dependencies. Can you check the value of the environment variable `AWS_EXECUTION_ENV`

**Comment by Sparticuz** [comment]
Actually node 18 wasn't supported until 108.2
